/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package rent_car1;

import javax.swing.JOptionPane;
import java.sql.Connection;
import java.sql.DriverManager;
import java.util.Arrays;
import javax.swing.JOptionPane;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import java.util.ArrayList;
import java.util.Iterator;
import java.io.BufferedWriter;
import java.io.FileWriter;
import java.time.LocalDate;
import java.time.Period;
import java.util.Properties;
import javax.mail.Message;
import javax.mail.MessagingException;
import javax.mail.PasswordAuthentication;
import javax.mail.Session;
import javax.mail.Transport;
import javax.mail.internet.InternetAddress;
import javax.mail.internet.MimeMessage;


/**
 *
 * @author OZN cOxat
 */
public class adaugareclienti extends javax.swing.JFrame {

    /**
     * Creates new form adaugareclienti
     * 
     */
    public adaugareclienti() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        Registerbut = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        predarelb = new javax.swing.JTextField();
        pretlb = new javax.swing.JTextField();
        eamillb = new javax.swing.JTextField();
        numelb = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        backbtn = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        nrilb = new javax.swing.JTextField();
        prenumlb = new javax.swing.JTextField();
        primirelb = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(228, 227, 241));
        jPanel1.setRequestFocusEnabled(false);

        jPanel2.setBackground(new java.awt.Color(180, 181, 181));

        Registerbut.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        Registerbut.setText("Adaugare");
        Registerbut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RegisterbutActionPerformed(evt);
            }
        });

        jLabel2.setIcon(new javax.swing.ImageIcon("C:\\Users\\OZN cOxat\\Documents\\faculta\\an 2\\pi\\rent_car1\\caricon.png")); // NOI18N
        jLabel2.setText("jLabel1");

        jLabel11.setFont(new java.awt.Font("Showcard Gothic", 0, 36)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("cleint nou");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(186, 186, 186)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(162, 162, 162)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel11)
                            .addComponent(Registerbut, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(165, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(41, 41, 41)
                .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(44, 44, 44)
                .addComponent(Registerbut, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        predarelb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                predarelbActionPerformed(evt);
            }
        });

        jLabel1.setText("Nume");

        jLabel3.setText("Prenume");

        jLabel5.setText("Email");

        jLabel6.setText("Pretul de plata ");

        backbtn.setText("Back");
        backbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backbtnActionPerformed(evt);
            }
        });

        jLabel7.setText("Numarul de inamtriculare");

        jLabel8.setText("Data predari");

        jLabel13.setText("Data atribuiri");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jLabel9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(backbtn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel3)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addComponent(jLabel5)))
                        .addGap(330, 1168, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(20, 20, 20)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel8)
                                    .addComponent(jLabel13)
                                    .addComponent(jLabel6))))
                        .addGap(35, 35, 35)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(eamillb, javax.swing.GroupLayout.PREFERRED_SIZE, 394, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(nrilb, javax.swing.GroupLayout.PREFERRED_SIZE, 394, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(prenumlb, javax.swing.GroupLayout.PREFERRED_SIZE, 394, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(numelb, javax.swing.GroupLayout.PREFERRED_SIZE, 394, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(predarelb, javax.swing.GroupLayout.PREFERRED_SIZE, 394, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(primirelb, javax.swing.GroupLayout.PREFERRED_SIZE, 394, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(pretlb, javax.swing.GroupLayout.PREFERRED_SIZE, 394, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addGap(17, 17, 17))
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGap(80, 80, 80)
                    .addComponent(jLabel10)
                    .addContainerGap(1174, Short.MAX_VALUE)))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(numelb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(prenumlb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(eamillb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nrilb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(5, 5, 5)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(primirelb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(predarelb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(pretlb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 218, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(backbtn)
                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(229, 229, 229))
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                    .addContainerGap(468, Short.MAX_VALUE)
                    .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(301, 301, 301)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(0, 6, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void predarelbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_predarelbActionPerformed

        // TODO add your handling code here:
    }//GEN-LAST:event_predarelbActionPerformed

    private void RegisterbutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RegisterbutActionPerformed
        // TODO add your handling code here:
       //vom folosi lista pentru a putea vrifica daca masina a mai fost atribuita sau nu 
       //adica vom salva in lita de fiecare data cand adaugam numarul de inmatriculare il vom salva in lita apoi il vom compara cu urmatorul element si in cazul in care sunt lafel vom primi o eroare.
      
        clienti client = new clienti();
        client.setNume(numelb.getText());
        client.setPrenume(prenumlb.getText());
        client.setPret_plata(Integer.valueOf(pretlb.getText()));
        client.setData_primire(primirelb.getText());
        client.setEmail(eamillb.getText());
        client.setNumar_inmatriculare(nrilb.getText());
        client.setDataretur(predarelb.getText());

        if(client.getNume().isEmpty() || client.getPrenume().isEmpty() || (client.getPret_plata()== 0) || client.getData_primire().isEmpty() || client.getDataretur().isEmpty() || client.getEmail().isEmpty() || client.getNumar_inmatriculare().isEmpty()){
            JOptionPane.showMessageDialog(this,"Toate campurile trebuie completate pentru a putea adauga un nou client","Error",JOptionPane.ERROR_MESSAGE);

        }
        else if(!client.isValidNume(client.getNume()))
        {
        JOptionPane.showMessageDialog(this,"Formatul numelui  este incorect","Error",JOptionPane.ERROR_MESSAGE);
        }
         else if(!client.isValidPrenume(client.getPrenume()))
        {
        JOptionPane.showMessageDialog(this,"Formatul Prenumelui  este incorect","Error",JOptionPane.ERROR_MESSAGE);
        }
        
        else if(!client.isValidNri(client.getNumar_inmatriculare())) 
        {
            JOptionPane.showMessageDialog(this,"Formatul numarului de inmatriculare este gresit  este incorect","Error",JOptionPane.ERROR_MESSAGE);
        }
        else if(!client.isValidEmail(client.getEmail()))
                {
        JOptionPane.showMessageDialog(this,"Formatul de email este incorect","Error",JOptionPane.ERROR_MESSAGE);
        }
        else
        {
          
              
               
               
               
               addclienti(client.getNume(),client.getPrenume(),client.getPret_plata(),client.getData_primire(),client.getDataretur(),client.getEmail(),client.getNumar_inmatriculare());
              // emailsend(client.getEmail(),client.getDataretur(),client.getNumar_inmatriculare());
               eamillb.setText(null);
               pretlb.setText(null);
               predarelb.setText(null);
               nrilb.setText(null);
               
               primirelb.setText(null); 
               pretlb.setText(null);
               prenumlb.setText(null);
               
               numelb.setText(null);
           }
                
                
       
    }//GEN-LAST:event_RegisterbutActionPerformed

    private void backbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backbtnActionPerformed
        // TODO add your handling code here:

        dispose();
        Mainpage m = new Mainpage();
        m.setVisible(true);
    }//GEN-LAST:event_backbtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(adaugareclienti.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(adaugareclienti.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(adaugareclienti.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(adaugareclienti.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new adaugareclienti().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Registerbut;
    private javax.swing.JButton backbtn;
    private javax.swing.JTextField eamillb;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTextField nrilb;
    private javax.swing.JTextField numelb;
    private javax.swing.JTextField predarelb;
    private javax.swing.JTextField prenumlb;
    private javax.swing.JTextField pretlb;
    private javax.swing.JTextField primirelb;
    // End of variables declaration//GEN-END:variables
public void addclienti(String nume,String Prenume,Integer pret,String dataprimire,String Dataretur,String mail,String numarinma){
 Connection dbconn = DBConnection.connectDB();
 //int ok = 0;
      if(dbconn !=null){
      try{
          int zielpret = 1;
          int vrstat = 0;
          PreparedStatement stistat=(PreparedStatement)
         dbconn.prepareStatement("SELECT stat from masini WHERE inma = ? ");
          stistat.setString(1, numarinma);
          ResultSet resstat = stistat.executeQuery();
          if(resstat.next())
          {
          vrstat = resstat.getInt("stat");
          }
          if(vrstat == 1)
          {    
          PreparedStatement sti=(PreparedStatement)
         dbconn.prepareStatement("SELECT inma from masini WHERE inma = ?");     
          
          sti.setString(1, numarinma);
          ResultSet res = sti.executeQuery();
          boolean existsindb1 = res.next();
          if(existsindb1){
          PreparedStatement sti2 = (PreparedStatement)
                  dbconn.prepareStatement("SELECT inma from clienti WHERE inma = ?"); 
              sti2.setString(1,numarinma);
              ResultSet res2 = sti2.executeQuery();
              boolean existindb2 = res2.next();
          if(existsindb1 && !existindb2){
              
              
              
              
            
                PreparedStatement st=(PreparedStatement)
                    dbconn.prepareStatement("INSERT INTO clienti(nume,prenume,email,inma,pret,dataretur,dataprimire) VALUES(?,?,?,?,?,?,?)");   
            st.setString(1, nume);
            st.setString(2, Prenume);
            st.setString(3,mail );
            st.setString(6,Dataretur);
            st.setString(4,numarinma);
            st.setString(7, dataprimire);
            st.setInt(5,pret);
       
         
            
            int rest= st.executeUpdate();
            
                
              PreparedStatement stpret=(PreparedStatement)
                    dbconn.prepareStatement("SELECT dataprimire, dataretur from clienti where inma = ?");
          stpret.setString(1,numarinma);
                  ResultSet respret = stpret.executeQuery();
                  LocalDate startDate =null;
                  LocalDate enddate = null;
                  
                  if(respret.next())
                  {
                  startDate = respret.getDate("dataprimire").toLocalDate();
                  enddate = respret.getDate("dataretur").toLocalDate();
                  }
                  Period period  = Period.between(startDate, enddate);
                zielpret = period.getDays();
                
                
                pret = pret *zielpret;
                
                    
                
            
            
                
                emailsend(mail,Dataretur,numarinma,pret);
          
                PreparedStatement stpret1=(PreparedStatement)
                    dbconn.prepareStatement("UPDATE clienti SET pret = ? WHERE inma = ?");
                    stpret1.setInt(1,pret);
                    stpret1.setString(2,numarinma);
                  stpret1.executeUpdate();
                  
                  
                  PreparedStatement sti5=(PreparedStatement)
         dbconn.prepareStatement("UPDATE masini SET stat = 0 WHERE inma = ?");
         sti5.setString(1, numarinma);
          sti5.executeUpdate();
                
                JOptionPane.showMessageDialog(this, "Datele clientului aufost salvate cu succes","Suces",JOptionPane.INFORMATION_MESSAGE);
          }
          else
          {PreparedStatement stver=(PreparedStatement)
                    dbconn.prepareStatement("SELECT * FROM clienti WHERE inma = ?");
          stver.setString(1, numarinma);
           ResultSet resver = stver.executeQuery();
           String datare = null;
           while(resver.next())
           { datare = resver.getString("dataretur");
           } 
          
              
              
              JOptionPane.showMessageDialog(this, "Masina dorita a fost deja atribuita unui client si va fi disponibila din data de "+ datare,"Suces",JOptionPane.INFORMATION_MESSAGE);
          }
          
          
                 
                  
          }
          else
          {
           JOptionPane.showMessageDialog(this, "Masina nu exista in baza noasta de date","ERROR",JOptionPane.INFORMATION_MESSAGE);
          }
              
          }
          else 
          {
          JOptionPane.showMessageDialog(this, "Masina pe care o doriti se afla momentan in mentenanta","ERROR",JOptionPane.INFORMATION_MESSAGE);
          }
          
          
    }catch(SQLException ex){
   Logger.getLogger(Register.class.getName()).log(Level.SEVERE, null, ex);
    }
    
    }
    else
    {
        JOptionPane.showMessageDialog(this, "NU MERE","ERORR",JOptionPane.INFORMATION_MESSAGE);
    System.out.println("Database connection failed");
    }
    
      
      }
public static void emailsend(String mail,String data,String nrin,int pret) {
        // Set system properties
        Properties props = new Properties();
        props.put("mail.smtp.auth", "true");
        props.put("mail.smtp.starttls.enable", "true");
        props.put("mail.smtp.host", "smtp.gmail.com");
        props.put("mail.smtp.port", "587");

        // Create a session
        Session session = Session.getInstance(props,
                new javax.mail.Authenticator() {
                    protected PasswordAuthentication getPasswordAuthentication() {
                        return new PasswordAuthentication("vlasancosmi@gmail.com", "lkfd avol tjzi dbyb");
                    }
                });

        try {
            // Create a message
            Message message = new MimeMessage(session);
            message.setFrom(new InternetAddress("vlasancosmi@gmail.com"));
            message.setRecipients(Message.RecipientType.TO,
                    InternetAddress.parse(mail));
            message.setSubject("Comfirmare comanda");
            message.setText("Buna ziua inchirierea dumneavoastra a fot realizata cu succes pentru masina cu numarul de inmatriculre"+nrin+" masina trebuie returnata pana in data de "+data+" pretul pe are va trebui sail platiti este :"+pret+"O zi buna ");

            // Send the message
            Transport.send(message);
            System.out.println("Email sent successfully.");
        } catch (MessagingException e) {
            throw new RuntimeException(e);
        }
    }


}

